plugins {
    id 'java'
    id 'application'
    id 'com.gradleup.shadow' version '8.3.5'
}

group = 'pitheguy'

version = '1.0.0'

repositories {
    mavenCentral()
    maven {url = 'https://maven.fabricmc.net'}
}

dependencies {
    implementation libs.jcef
    implementation libs.vineflower
    implementation libs.gson
    implementation libs.guava
    implementation libs.mcsrc
    implementation libs.jopt
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

sourceSets {
    main {
        java {
            srcDirs = ['src/main/java']
        }
    }
}

application {
    mainClass = 'pitheguy.mcsrcdesktop.Main'
}

tasks.register('dev', JavaExec) {
    group = 'application'
    description = 'Runs the application in dev mode'
    classpath = sourceSets.main.runtimeClasspath
    mainClass = application.mainClass
    args '--dev'
}